POST http://localhost:5050/test
Content-Type: application/json

{
  "username" : "omar",
  "email" : "o@o.c",
  "password" : "password",
  "teacherId" : 1,
  "role" : "student"
}


###

POST http://localhost:5050/login
Content-Type: application/json


{
    "userid" : "o@o.c",
    "password": "password"
}


###
GET http://localhost:5050/users
Content-Type: application/json
