POST http://localhost:5050/test
Content-Type: application/json

{
  "username" : "omar",
  "email" : "o@o.c",
  "password" : "password",
  "teacherId" : 1,
  "role" : "student"
}


###

POST http://localhost:5050/login
Content-Type: application/json


{
    "userid" : "o@o.c",
    "password": "password"
}


###
GET http://localhost:5050/lessons/4
Content-Type: application/json


###
GET http://localhost:5050/partners
Content-Type: application/json


###
DELETE http://localhost:5050/delete_lesson/3
Content-Type: application/json

###
GET http://localhost:5050/drivers/1
Content-Type: application/json

